#path a tutti gli "esecutori", softwares (quindi pvbatch, simvascular, svmultiphysics etc)

#paraview 
pvpython: "/home/trentodoc/APPS/ParaView-6.2.0-RC1-MPI-Linux-Python3.12-x86_64/bin/pvpython"

#3dslicer
slicer: "/home/trentodoc/APPS/Slicer-5.12.3-linux-amd64/Slicer"

#SIMVASCULAR
simvascular: "/usr/local/sv/simvascular/2026-06-08/simvascular"