#config/pipeline.yaml
#gestisce la sequenza degli stadi per ogni pz + il tipo di stadio (auto,interactive,gate,asyncrone)
schema_version: 1 

stages: 
- name: paraview #transorm, scale, clean, triangulate 
  type: auto

- name: sv_faces  #crea SV folder, importa modello e combina segmenti di wall, inserisce type di wall, caps o inlet --> revisione umana?
  type: interactive

- name: sv_mesh  #remesh, BL, GMES, portion edge size da 0.5 decrescente
  type: auto

- name: mesh_qc #gate del quality check inferiore a threshold (400?)  + ESTRAZIONE MODELFACE ID 
  type: gate 

- name: sv_bc #calculate bc w/ setup_bcs.py, insert, change solver params
  type: auto 

- name: simulation #launch and run sim 
  type: async 



